on: issue_comment
name: Label command
jobs:
  check_comments:
      name: Check comments for /label
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Check for label
          id: command
          run: ./.github/actions/label.sh
          env:
              GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
